### ISSUE TITLE
Currencies v1.0.0

### ISSUE THREAD

**Issue by arcanedev-maroc** [ARCANEDEV/Currencies#3]
### TODO:
- [x] Adding cURL Http Client.
- [x] Adding basic exchanges services.
  - [x] https://openexchangerates.org/
  - [x] https://currencylayer.com/ (#9)
- [x] Adding a currency validator (#6).
- [ ] Adding the Facades.
- [ ] Blade directives for currencies.
### Suggestions:
- [ ] Adding `API Free` converters:
  - [ ] Database Store.
  - [ ] Config/Array Store.
  - [ ] File Store (json file).
